AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  orders-api

  Sample SAM Template for orders-api

Globals:
  Function:
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable
        CUSTOMERS_TABLE: !Ref CustomersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CustomersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi
      Handler: uz.ulugbek.aws.lambda.orderapi.CreateOrderLambda::createOrder
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  ReadOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi
      Handler: uz.ulugbek.aws.lambda.orderapi.ReadOrdersLambda::getOrders
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
  CreateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi
      Handler: uz.ulugbek.aws.lambda.orderapi.CreateCustomerLambda::createCustomer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CustomersTable
      Events:
        CustomerEvents:
          Type: Api
          Properties:
            Path: /customers
            Method: POST
  ReadCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi
      Handler: uz.ulugbek.aws.lambda.orderapi.ReadCustomerLambda::getCustomers
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CustomersTable
      Events:
        CustomerEvents:
          Type: Api
          Properties:
            Path: /customers
            Method: GET

Outputs:
  CreateOrdersAPI:
    Description: "API Gateway endpoint url for create orders function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
  CreateOrderFunction:
    Description: "Create Order Lambda Function ARN"
    Value: !GetAtt CreateOrderFunction.Arn
  CreateOrderFunctionIamRole:
    Description: "Create Order Lambda Function IAM Role ARN"
    Value: !GetAtt CreateOrderFunctionRole.Arn





