version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "firstlambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hqb7wl4c23cj"
s3_prefix = "firstlambda"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
