AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patientcheckout

  Sample SAM Template for patientcheckout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512
    Timeout: 20

Resources:
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic
  PatientCheckoutLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patientcheckout
      Handler: uz.ulugbek.aws.lambda.s3sns.PatientCheckoutLambda::handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PatientCheckoutTopic.TopicName
      Environment: 
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 
      Events:
        S3Event:
          Type: S3 
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
  BillManagementLambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: patientcheckout
      Handler: uz.ulugbek.aws.lambda.s3sns.BillManagementLambda::handler
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutTopic
# assignment
  StudentCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub student-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  StudentCheckoutTopic:
    Type: AWS::SNS::Topic
  StudentCheckoutLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patientcheckout
      Handler: uz.ulugbek.aws.lambda.s3sns.StudentS3Listener::studentHandler
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub student-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt StudentCheckoutTopic.TopicName
      Environment: 
        Variables:
          STUDENT_CHECKOUT_TOPIC: !Ref StudentCheckoutTopic
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 
      Events:
        S3Event:
          Type: S3 
          Properties:
            Bucket: !Ref StudentCheckoutBucket
            Events: s3:ObjectCreated:*
  StudentSNSListenerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: patientcheckout
      Handler: uz.ulugbek.aws.lambda.s3sns.StudentSNSListener::studentHandler
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref StudentCheckoutTopic

