version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build1 started on `date`
  post_build:
    commands:
      - echo Build1 completed on `date`
      - aws cloudformation package --template-file template.yaml --s3-bucket cicd-module-lambda --output-template-file outputSamTemplate.yml
artifacts:
  files:
    - outputSamTemplate.yml