version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "module-9-uploads-batch-notifier"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t8uocqjmtdoc"
s3_prefix = "module-9-uploads-batch-notifier"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
